import { StyleSheet } from 'react-native';

const signup = StyleSheet.create({
  container: {
    backgroundColor: '#ECFBFF',
    padding: 10,
    flex: 1,
  },
  // SIGN UP PAGES
  ciscLogo: {
    width: 90,
    height: 33,
    maxWidth: 90,
    maxHeight: 33,
  },
  label: {
    fontSize: 35,
    fontFamily: 'Satoshi-Bold',
    textShadowColor: '#0000004D',
    textShadowOffset: { width: 4, height: 0 },
    textShadowRadius: 10,
    textAlign: 'center',
  },
  subLabel: {
    fontSize: 20,
    fontFamily: 'Satoshi-Bold',
    textShadowColor: '#0000004D',
    textShadowOffset: { width: 4, height: 0 },
    textShadowRadius: 10,
    textAlign: 'center',
  },
  defaultProfile: {
    width: 100,
    height: 100,
    maxWidth: 100,
    maxHeight: 100,
    borderRadius: 65,
    alignSelf: 'center',
    marginTop: 10,
  },
  cameraBackground: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#57b8b3',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  cameraIcon: {
    width: 16,
    height: 16,
    tintColor: '#fff',
  },
  //   STEPS INDICATOR DESIGN
  stepsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  stepCircle: {
    width: 24,
    height: 24,
    maxHeight: 24,
    maxWidth: 24,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: 'black',
    marginHorizontal: 5,
  },
  activateStep: {
    backgroundColor: '#9EEBCB',
    borderRadius: 17.5,
  },
  inactivateStep: {
    backgroundColor: '#D9D9D9',
    borderRadius: 17.5,
  },

  //    FORMS
  textform: {
    textAlign: 'left',
    fontSize: 15,
    fontFamily: 'Satoshi-Bold',
    marginHorizontal: 20,
  },
  textInputForm: {
    width: 350,
    height: 40,
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
    backgroundColor: 'white',
    elevation: 5,
    maxWidth: 350,
    maxHeight: 40,
    alignSelf: 'center',
    marginVertical: 2,
    fontFamily: 'Satoshi-Medium',
  },
  dateText: {
    textAlign: 'left',
    alignItems: 'flex-start',
    fontSize: 15,
    fontFamily: 'Satoshi-Regular',
    marginHorizontal: 20,
  },
  dateInput: {
    flexDirection: 'row',
    maxWidth: 350,
    maxHeight: 40,
    width: 350,
    height: 40,
    borderRadius: 5,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    elevation: 5,
    marginBottom: 10,
    fontFamily: 'Satoshi-Medium',
  },
  icon: {
    maxWidth: 24,
    maxHeight: 24,
    alignItems: 'flex-end',
    marginRight: 15,
  },
  number: {
    fontWeight: 'bold',
    fontSize: 12,
    fontFamily: 'Satoshi-Medium',
  },

  // Select component (Dropdown)
  dropdownButton: {
    flexDirection: 'row',
    maxWidth: 350,
    maxHeight: 40,
    width: 350,
    height: 40,
    borderRadius: 5,
    backgroundColor: '#fff',
    justifyContent: 'flex-end',
    alignSelf: 'center',
    elevation: 5,
  },

  dropdownArrowicon: {
    marginLeft: 180,
  },

  dropdownContainer: {
    backgroundColor: '#fff',
    maxWidth: 350,
    maxHeight: 40,
    width: 350,
    height: 40,
    justifyContent: 'center',
    alignSelf: 'center',
    elevation: 5,
    borderRadius: 5,
  },

  // COMPLETE SIGN UP PAGE
  completeSignUpContainer: {
    flex: 1,
    backgroundColor: '#ECFBFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  video: {
    width: 412,
    height: 412,
    marginBottom: 20,
    borderRadius: 20,
    overflow: 'hidden',
    maxWidth: 412,
    maxHeight: 412,
  },
  completeTitle: {
    color: '#2CA96A',
    fontFamily: 'Satoshi-Bold',
    fontSize: 35,
    textShadowColor: '#0000004D',
    textShadowOffset: { width: 4, height: 0 },
    textShadowRadius: 10,
    width: 400,
    textAlign: 'center',
  },
  completeStatement: {
    textAlign: 'justify',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 50,
    fontSize: 15,
    fontFamily: 'Satoshi-Regular',
  },
  completeNextButton: {
    backgroundColor: '#2CA96A',
    borderRadius: 5,
    width: 370,
    height: 40,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    fontFamily: 'Satoshi-Medium',
    maxWidth: 370,
    maxHeight: 40,
    marginBottom: 10,
    marginTop: 20,
  },
});

export default signup;
