import { MiscueType } from "./miscue";

/**
 * TYPES OF USER ROLES
 *  - used in base user information
 */
export type UserRole = 'student' | 'faculty' | 'admin';


/**
 * USER DOCUMENT INTERFACE
 * - used to store user information
 */
export interface UserDocument {
  // USER ID
  uid: string;
  email: string;
  role: string;

  // USER PROFILE INFORMATION
  profileImageUrl?: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  sex: string;

  // ROLE SPECIFIC DATA
  // Student specific data
  studentData?: {
    gradeLevel: number;
    dateOfBirth: string;
    classId?: string;
    reading_Level?: 'beginner' | 'intermediate' | 'advanced';
  };

  // Faculty specific data
  facultyData?: {
    assignedGradeLevels: number[];
    assignedClassIds: string[];
  };

  // Creation and update from Firestore Timestamp
  createdAt: any; 
  updatedAt?: any; 
}

/**
 * CLASS DOCUMENT INTERFACE
 * - used to store class information
 */
export interface ClassDocument {
  // Class specific data
  classId: string; // Automatically generated by the system
  classCode: string; // Human-readable code, e.g., "GR1-A" where code is generated for the students to join
  className?: string; // Optional: full class name
  gradeLevel: number; 

  // References
  facultyId: string; // Reference to the faculty document (UID)
  studentIds: string[]; // Reference to the student documents (UIDs)

  // META
  isActive: boolean;
  // Creation and update from Firestore Timestamp
  createdAt: any; 
  updatedAt?: any; 
}

/**
 * MISCUE REPORT DOCUMENT INTERFACE
 * - used to store miscue report information
 */
export interface MiscueReportDocument {
  reportId: string;
  studentId: string;
  classId: string; // Reference to the class document (UID)

  // Passage Information
  passageTitle: string;
  passageText: string;

  // Miscue Data (Stored in Array for Flexibility)
  miscues: {
    type: MiscueType;
    expectedWord: string; // Word in passage
    spokenWord?: string; // What student said (null for omissions)
    position?: number;  // Position in the passage (word index)
  }[];
  
  // Performance Metrics
  accuracyRate: number;
  recordingDuration?: number;

  // Creation from Firestore Timestamp
  createdAt: any;
}



