import { StyleSheet } from 'react-native';
import { FacultyColors, Radii, Shadows } from '../Utilities/Theme';

const adminUserManagement = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: FacultyColors.bg,
  },
  container: {
    flex: 1,
    backgroundColor: FacultyColors.bg,
  },
  content: {
    flex: 1,
  },
  headerSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: FacultyColors.white,
    borderRadius: Radii.md,
    paddingHorizontal: 16,
    height: 50,
    ...Shadows.subtle,
  },
  filterTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: FacultyColors.white + '80',
    padding: 4,
    borderRadius: 16,
  },
  filterTab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    marginHorizontal: 2,
  },
  filterTabActive: {
    backgroundColor: FacultyColors.primaryDeep,
    ...Shadows.card,
  },
  filterTabText: {
    fontSize: 12,
    fontWeight: '800',
    color: FacultyColors.slate,
  },
  filterTabTextActive: {
    color: FacultyColors.white,
  },
  userCount: {
    fontSize: 13,
    fontWeight: '700',
    color: FacultyColors.slate,
    marginBottom: 8,
  },
  errorContainer: {
    alignItems: 'center',
    marginTop: 40,
    paddingHorizontal: 20,
  },
  errorText: {
    fontSize: 14,
    fontWeight: '600',
    color: FacultyColors.red,
    textAlign: 'center',
  },
  listWrapper: {
    flex: 1,
  },
  listContainer: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  userCard: {
    flexDirection: 'row',
    backgroundColor: FacultyColors.white,
    borderRadius: Radii.lg,
    padding: 16,
    marginBottom: 12,
    alignItems: 'center',
    ...Shadows.card,
    overflow: 'visible',
  },
  userCardContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 14,
  },
  userAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: FacultyColors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  roleIconBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: FacultyColors.white,
    borderRadius: 10,
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    ...Shadows.subtle,
    borderWidth: 1.5,
    borderColor: FacultyColors.primaryLight,
  },
  roleIconText: {
    fontSize: 10,
    lineHeight: 12,
  },
  userInfo: {
    flex: 1,
    marginRight: 12,
  },
  userName: {
    fontSize: 15,
    fontWeight: '800',
    color: FacultyColors.ink,
    marginBottom: 2,
  },
  userEmail: {
    fontSize: 12,
    color: FacultyColors.slate,
    marginBottom: 6,
  },
  userMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  userMetaChip: {
    backgroundColor: FacultyColors.primaryPale,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  userMetaLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: FacultyColors.primary,
    textTransform: 'uppercase',
  },
  userMetaValue: {
    fontSize: 9,
    fontWeight: '700',
    color: FacultyColors.primaryDeep,
  },
  arrowContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
    position: 'relative',
    alignSelf: 'stretch',
  },
  arrowButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: FacultyColors.bg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionsButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: FacultyColors.bg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionsMenu: {
    position: 'absolute',
    right: 0,
    top: 8,
    backgroundColor: FacultyColors.white,
    borderRadius: 12,
    ...Shadows.card,
    minWidth: 140,
    zIndex: 9999,
    elevation: 10,
    overflow: 'hidden',
  },
  optionsMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 10,
  },
  optionsMenuText: {
    fontSize: 13,
    fontWeight: '700',
    color: FacultyColors.ink,
  },
  optionsMenuDivider: {
    height: 1,
    backgroundColor: FacultyColors.slatePale,
    marginHorizontal: 10,
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: 100,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: FacultyColors.ink,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    color: FacultyColors.slate,
    fontWeight: '600',
    textAlign: 'center',
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadMoreButton: {
    backgroundColor: FacultyColors.white,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 20,
    ...Shadows.subtle,
    borderWidth: 1,
    borderColor: FacultyColors.primaryLight,
  },
  loadMoreText: {
    fontSize: 14,
    fontWeight: '800',
    color: FacultyColors.primary,
  },
  fullScreenModal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  fullScreenContainer: {
    backgroundColor: FacultyColors.white,
    borderRadius: 32,
    width: '100%',
    maxHeight: '90%',
    padding: 24,
    flexShrink: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: FacultyColors.ink,
  },
  closeTxt: {
    fontSize: 22,
    color: FacultyColors.slate,
    fontWeight: '700',
  },
  field: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: FacultyColors.slate,
    marginBottom: 8,
  },
  modalInput: {
    backgroundColor: FacultyColors.bg,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: FacultyColors.ink,
    fontWeight: '600',
    borderWidth: 1,
    borderColor: '#eee',
  },
  saveActionBtn: {
    backgroundColor: FacultyColors.primaryDeep,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginTop: 10,
    ...Shadows.button,
  },
  saveActionTxt: {
    color: FacultyColors.white,
    fontSize: 16,
    fontWeight: '800',
  },
});

export default adminUserManagement;