import { StyleSheet } from 'react-native';

const buttons = StyleSheet.create({
  nextPageButton: {
    backgroundColor: '#2CA96A',
    borderRadius: 5,
    width: 320,
    height: 40,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    maxWidth: 350,
    maxHeight: 40,
    marginBottom: 10,
    marginTop: 35,
  },
  nextPageText: {
    color: '#FFFF',
    fontSize: 25,
    fontFamily: 'DynaPuff-Bold'
  },
  // CANCEL BUTTON
  cancelButton: {
    backgroundColor: '#ffff',
    borderWidth: 0.5,
    borderColor: '#FE5A59',
    borderRadius: 5,
    width: 320,
    height: 40,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    maxWidth: 350,
    maxHeight: 40,
  },
  cancelText: {
    color: '#FE5A59',
    fontSize: 25,
    fontFamily: 'DynaPuff-Bold'
  },
  // START READING BUTTON
  startReadingButton: {
    backgroundColor: '#3D71D9',
    borderRadius: 50,
    width: 367,
    height: 50,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    maxWidth: 367,
    maxHeight: 50,
    marginTop: 50,
  },
    // READING HISTORY BUTTON
    readingHistoryButton: {
    backgroundColor: '#3D71D9',
    borderRadius: 50,
    width: 367,
    height: 50,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    maxWidth: 367,
    maxHeight: 50,
    marginTop: 15,
  },
  // CHOOSE ROLE BUTTON
  studentButton: {
    backgroundColor: '#3D71D9',
    borderRadius: 5,
    width: 320,
    height: 40,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    maxWidth: 350,
    maxHeight: 40,
    marginTop: 15,
  },
  teacherButton: {
    backgroundColor: '#3D71D9',
    borderRadius: 5,
    width: 320,
    height: 40,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    maxWidth: 350,
    maxHeight: 40,
    marginTop: 15,
  },
  sexRadioButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 350,
    height: 40,
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
    backgroundColor: 'white',
    elevation: 5,
    maxWidth: 350,
    maxHeight: 40,
    alignSelf: 'center',
    marginVertical: 2,
    fontFamily: 'Satoshi-Medium',
  }
});

export default buttons;
