import { StyleSheet, Dimensions } from 'react-native';
import { sw, sh, sf } from '../Utils/responsive';

const { width: screenWidth } = Dimensions.get('window');

// Common button width – 90% of screen, capped at 367 (or original max)
const buttonWidth = Math.min(screenWidth - sw(40), sw(367));
const signUpButtonWidth = Math.min(screenWidth - sw(40), sw(350));

const buttons = StyleSheet.create({
  nextPageSignUpButton: {
    backgroundColor: '#3D71D9',
    borderRadius: sw(5),
    width: signUpButtonWidth,
    height: sh(40),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: sh(10),
    marginTop: sh(35),
  },
  nextPageSignUpText: {
    color: '#FFFF',
    fontSize: sf(20),
    fontFamily: 'Satoshi-Black',
  },
  cancelSignUpButton: {
    backgroundColor: '#ffff',
    borderWidth: 0.5,
    borderColor: '#FE5A59',
    borderRadius: sw(5),
    width: signUpButtonWidth,
    height: sh(40),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  cancelSignUpText: {
    color: '#FE5A59',
    fontSize: sf(20),
    fontFamily: 'Satoshi-Bold',
  },
  nextPageButton: {
    backgroundColor: '#3D71D9',
    borderRadius: sw(5),
    width: buttonWidth,
    height: sh(40),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: sh(10),
    marginTop: sh(35),
  },
  nextPageText: {
    color: '#FFFF',
    fontSize: sf(25),
    fontFamily: 'DynaPuff-Bold',
  },
  cancelButton: {
    backgroundColor: '#ffff',
    borderWidth: 0.5,
    borderColor: '#FE5A59',
    borderRadius: sw(5),
    width: buttonWidth,
    height: sh(40),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  cancelText: {
    color: '#FE5A59',
    fontSize: sf(25),
    fontFamily: 'DynaPuff-Bold',
  },
  startReadingButton: {
    backgroundColor: '#3D71D9',
    borderRadius: sw(50),
    width: buttonWidth,
    height: sh(50),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: sh(50),
  },
  readingHistoryButton: {
    backgroundColor: '#3D71D9',
    borderRadius: sw(50),
    width: buttonWidth,
    height: sh(50),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: sh(15),
  },
  studentButton: {
    backgroundColor: '#3D71D9',
    borderRadius: sw(5),
    width: buttonWidth,
    height: sh(40),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: sh(15),
  },
  teacherButton: {
    backgroundColor: '#3D71D9',
    borderRadius: sw(5),
    width: buttonWidth,
    height: sh(40),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: sh(15),
  },
  sexRadioButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: signUpButtonWidth,
    height: sh(40),
    borderRadius: sw(5),
    padding: sw(10),
    marginBottom: sh(10),
    backgroundColor: 'white',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    alignSelf: 'center',
    marginVertical: sh(2),
    fontFamily: 'Satoshi-Medium',
  },
});

export default buttons;