import { StyleSheet } from 'react-native';
import { sw, sh, sf } from '../Utils/responsive';

const facultyProfile = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ECFBFF',
  },
  insideContainer: {
    flex: 1,
    position: 'relative',
    paddingTop: sh(10),
    paddingHorizontal: sw(20),
    zIndex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: sh(40),
  },
  titleGroup: {
    alignItems: 'center',
    marginVertical: sh(25),
  },
  screenTitle: {
    fontSize: sf(28),
    fontFamily: 'DynaPuff-Bold',
    color: '#3B7FC9',
  },
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: sw(25),
    paddingTop: sh(65),
    paddingBottom: sh(30),
    paddingHorizontal: sw(24),
    marginTop: sh(40),
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(6) },
    shadowOpacity: 0.15,
    shadowRadius: sw(12),
    borderWidth: 2,
    borderColor: '#E8F4FF',
    position: 'relative',
  },
  avatarContainer: {
    position: 'absolute',
    top: sh(-45),
    alignSelf: 'center',
    width: sw(100),
    height: sw(100),
    borderRadius: sw(50),
    backgroundColor: '#38B6FF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#3B7FC9',
    shadowOffset: { width: 0, height: sw(4) },
    shadowOpacity: 0.3,
    shadowRadius: sw(6),
    borderWidth: 4,
    borderColor: '#FFFFFF',
    zIndex: 10,
  },
  avatarIcon: {
    width: sw(92),
    height: sw(92),
    borderRadius: sw(46),
  },
  inputGroup: {
    marginBottom: sh(18),
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: sw(12),
  },
  halfInputGroup: {
    flex: 1,
    marginBottom: sh(18),
  },
  label: {
    fontSize: sf(14),
    fontFamily: 'Satoshi-Bold',
    color: '#3B7FC9',
    marginBottom: sh(6),
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  textInput: {
    backgroundColor: '#F4F9FF',
    borderWidth: 1.5,
    borderColor: '#B8E8F8',
    borderRadius: sw(15),
    paddingHorizontal: sw(16),
    paddingVertical: sh(12),
    fontSize: sf(16),
    fontFamily: 'Satoshi-Medium',
    color: '#2C2C2C',
  },
  textInputDisabled: {
    backgroundColor: '#F5F5F5',
    borderColor: '#E0E0E0',
    color: '#777777',
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: sh(15),
    gap: sw(15),
  },
  editButton: {
    backgroundColor: '#E8F4FF',
    borderWidth: 2,
    borderColor: '#38B6FF',
    paddingVertical: sh(14),
    paddingHorizontal: sw(25),
    borderRadius: sw(20),
    width: '100%',
    alignItems: 'center',
  },
  editButtonText: {
    color: '#3B7FC9',
    fontFamily: 'Satoshi-Bold',
    fontSize: sf(16),
  },
  saveButton: {
    backgroundColor: '#38B6FF',
    paddingVertical: sh(14),
    paddingHorizontal: sw(25),
    borderRadius: sw(20),
    flex: 1,
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#38B6FF',
    shadowOffset: { width: 0, height: sw(4) },
    shadowOpacity: 0.3,
    shadowRadius: sw(6),
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Satoshi-Bold',
    fontSize: sf(16),
  },
  cancelButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#FF7043',
    paddingVertical: sh(12),
    paddingHorizontal: sw(25),
    borderRadius: sw(20),
    flex: 1,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#FF7043',
    fontFamily: 'Satoshi-Bold',
    fontSize: sf(16),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
export default facultyProfile;
