import { StyleSheet } from 'react-native';
import { sw, sh, sf } from '../Utils/responsive';

// ─── Palette (mirrors Student_Home) ──────────────────────────────────────────
const C = {
  green:      '#2ca96a',
  greenDark:  '#008443',
  greenDeep:  '#005028',
  greenLight: '#c0e8f2',
  greenPale:  '#E8F5E9',
  bg:         '#F1FBF4',
  white:      '#ffffff',
  ink:        '#1B2B22',
  inkLight:   '#6B8E6B',
  slate:      '#A5B8A7',
  border:     '#C8E6C9',
  inputBg:    '#F6FBF7',
  coral:      '#FF7043',
  disabled:   '#A5D6B0',
};

const login = StyleSheet.create({
  // ========== CONTAINER ==========
  safeAreaContainer: {
    flex: 1,
    backgroundColor: C.bg,
  },
  scrollContent: {
    flexGrow: 1,
    paddingVertical: sh(40),
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ========== LOGO SECTION ==========
  logoSection: {
    alignItems: 'center',
    zIndex: 1,
    width: sw(280),
    height: sw(280),
    borderRadius: sw(140),
    overflow: 'hidden',
  },
  video: {
    width: '100%',
    height: '100%',
    borderRadius: sw(140),
    elevation: 20,
    shadowColor: C.greenDark,
    shadowOffset: { width: 0, height: sw(10) },
    shadowOpacity: 0.35,
    shadowRadius: sw(13.16),
  },

  // ========== ERROR CONTAINER ==========
  errorContainer: {
    width: '100%',
    maxWidth: sw(340),
    backgroundColor: '#FEF2F2',
    borderRadius: sw(12),
    padding: sw(8),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: sh(10),
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(1) },
    shadowOpacity: 0.12,
    shadowRadius: sw(2.22),
  },
  errorIconCircle: {
    width: sw(32),
    height: sw(32),
    borderRadius: sw(16),
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: sw(12),
  },
  errorIcon: {
    fontSize: sf(18),
    fontFamily: 'Nunito-Bold',
    color: '#DC2626',
  },
  errorText: {
    flex: 1,
    fontSize: sf(13),
    fontFamily: 'Nunito-Medium',
    color: '#991B1B',
    lineHeight: sf(18),
  },

  // ========== INPUT FIELDS ==========
  inputWrapper: {
    width: '100%',
    maxWidth: sw(340),
    marginBottom: sh(10),
  },
  inputLabel: {
    fontSize: sf(14),
    fontFamily: 'Nunito-Bold',
    color: C.ink,
    marginBottom: sh(8),
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    borderRadius: sw(14),
    paddingHorizontal: sw(8),
    paddingVertical: sh(5),
    borderWidth: 1.5,
    borderColor: C.border,
    shadowColor: C.greenDark,
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.06,
    shadowRadius: sw(4),
    elevation: 2,
  },
  iconContainer: {
    width: sw(32),
    height: sw(32),
    borderRadius: sw(10),
    backgroundColor: C.greenPale,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: sw(12),
  },
  inputIcon: {
    fontSize: sf(16),
  },
  input: {
    flex: 1,
    fontSize: sf(15),
    fontFamily: 'Nunito-Medium',
    color: C.ink,
  },

  // ========== LOGIN BUTTON ==========
  loginButton: {
    width: '100%',
    maxWidth: sw(340),
    backgroundColor: C.green,
    borderRadius: sw(14),
    paddingVertical: sh(16),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sh(8),
    marginBottom: sh(24),
    shadowColor: C.greenDark,
    shadowOffset: { width: 0, height: sw(4) },
    shadowOpacity: 0.3,
    shadowRadius: sw(8),
    elevation: 5,
  },
  loginButtonDisabled: {
    backgroundColor: C.disabled,
    shadowOpacity: 0,
    elevation: 0,
  },
  loginButtonText: {
    fontSize: sf(16),
    fontFamily: 'Nunito-ExtraBold',
    color: C.white,
    letterSpacing: 0.4,
  },

  // ========== DIVIDER ==========
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: sw(340),
    marginBottom: sh(20),
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: C.border,
  },
  dividerText: {
    fontSize: sf(12),
    fontFamily: 'Nunito-Medium',
    color: C.inkLight,
    marginHorizontal: sw(16),
  },

  // ========== REGISTER SECTION ==========
  registerSection: {
    width: '100%',
    maxWidth: sw(340),
    alignItems: 'center',
  },
  registerPrompt: {
    fontSize: sf(14),
    fontFamily: 'Nunito-Medium',
    color: C.inkLight,
    textAlign: 'center',
    marginBottom: sh(16),
  },
  registerLink: {
    fontSize: sf(13),
    fontFamily: 'Nunito-Bold',
    color: C.green,
    textDecorationLine: 'underline',
  },
  registerButtonsContainer: {
    width: '100%',
    gap: sh(12),
  },

  // ========== SIGNUP BUTTONS ==========
  signupwithgooglebutton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.white,
    borderRadius: sw(14),
    paddingVertical: sh(14),
    paddingHorizontal: sw(16),
    borderWidth: 1.5,
    borderColor: C.border,
    shadowColor: C.greenDark,
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.07,
    shadowRadius: sw(4),
    elevation: 2,
  },
  signupwithemailbutton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.white,
    borderRadius: sw(14),
    paddingVertical: sh(14),
    paddingHorizontal: sw(16),
    borderWidth: 1.5,
    borderColor: C.border,
    shadowColor: C.greenDark,
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.07,
    shadowRadius: sw(4),
    elevation: 2,
  },
  googleimage: {
    width: sw(24),
    height: sw(24),
    marginRight: sw(12),
  },
  registerText: {
    fontSize: sf(15),
    fontFamily: 'Nunito-Bold',
    color: C.ink,
  },

  // ========== LEGACY STYLES ==========
  label: {
    marginTop: sh(5),
    alignSelf: 'flex-start',
    marginStart: sw(10),
    marginBottom: sh(5),
    fontFamily: 'Nunito-Medium',
    fontSize: sf(15),
  },
  forgotpass: {
    alignSelf: 'flex-end',
    marginBottom: sh(10),
    fontSize: sf(13),
    fontFamily: 'Nunito-Regular',
    textDecorationLine: 'underline',
    color: C.green,
  },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textinput: {
    width: '100%',
    borderRadius: sw(5),
    padding: sw(10),
    marginBottom: sh(10),
    backgroundColor: C.white,
    fontFamily: 'Nunito-Medium',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    maxWidth: sw(350),
    maxHeight: sh(40),
    color: C.ink,
  },
  button: {
    backgroundColor: C.green,
    borderRadius: sw(5),
    width: sw(320),
    height: sh(40),
    elevation: 5,
    shadowColor: C.greenDark,
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: sw(350),
    maxHeight: sh(40),
  },
  buttonText: {
    color: C.white,
    fontSize: sf(16),
    fontFamily: 'Nunito-Black',
  },
  notRegisteredContainer: {
    backgroundColor: C.bg,
    alignItems: 'center',
    paddingBottom: sh(40),
    paddingTop: sh(20),
    paddingHorizontal: sw(20),
  },
  notRegisteredAlignment: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: sw(350),
  },
  leftLine: {
    flex: 2,
    height: 1,
    backgroundColor: C.border,
    opacity: 0.6,
  },
  notRegisteredText: {
    fontSize: sf(12),
    color: C.inkLight,
    fontWeight: '400',
    letterSpacing: 0.2,
    textAlign: 'center',
    marginHorizontal: sw(16),
    fontFamily: 'Nunito-Medium',
  },
  rightLine: {
    flex: 2,
    height: 1,
    backgroundColor: C.border,
    opacity: 0.6,
  },
  textInputError: {
    borderColor: '#EF4444',
    backgroundColor: '#FFF5F5',
    borderWidth: 2,
  },
  textInputValid: {
    borderColor: C.green,
    borderWidth: 1.5,
  },
  requiredStar: {
    color: '#EF4444',
    fontSize: sf(16),
  },
  buttonDisabled: {
    backgroundColor: C.disabled,
    opacity: 0.7,
  },
  forgotPassButton: {
    alignSelf: 'flex-end',
    marginEnd: sw(25),
    marginBottom: sh(10),
  },
});

export default login;