import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

// Define a responsive width for form elements (90% of screen, but not wider than 350)
const formWidth = Math.min(screenWidth - 40, 350);

const signup = StyleSheet.create({
  container: {
    backgroundColor: '#f2f6ff',
    padding: 20,
    flex: 1,
  },
  ciscLogo: {
    width: 90,
    height: 33,
    alignSelf: 'center', // Center logo
    marginVertical: 10,
  },
  label: {
    fontSize: 35,
    fontFamily: 'Satoshi-Bold',
    textShadowColor: '#0000004D',
    textShadowOffset: { width: 4, height: 0 },
    textShadowRadius: 10,
    textAlign: 'center',
    marginVertical: 10,
  },
  subLabel: {
    fontSize: 20,
    fontFamily: 'Satoshi-Black',
    textAlign: 'center',
    color: '#3B7FC9',
    marginBottom: 20,
  },
  defaultProfile: {
    width: 100,
    height: 100,
    borderRadius: 65,
    alignSelf: 'center',
    marginTop: 10,
  },
  cameraBackground: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#57b8b3',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  cameraIcon: {
    width: 16,
    height: 16,
    tintColor: '#fff',
  },
  stepsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  stepCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: 'black',
    marginHorizontal: 10,
  },
  activateStep: {
    backgroundColor: '#3B7FC9',
  },
  inactivateStep: {
    backgroundColor: '#FFFFFF',
  },
  // Form elements
  textform: {
    textAlign: 'left',
    fontSize: 15,
    fontFamily: 'Satoshi-Bold',
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 5,
  },
  textInputForm: {
    width: formWidth,
    height: 40,
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
    backgroundColor: 'white',
    elevation: 5,
    alignSelf: 'center',
    fontFamily: 'Satoshi-Medium',
    color: 'black',
  },
  dateText: {
    textAlign: 'left',
    fontSize: 15,
    fontFamily: 'Satoshi-Regular',
    marginHorizontal: 20,
  },
  dateInput: {
    flexDirection: 'row',
    width: formWidth,
    height: 40,
    borderRadius: 5,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    elevation: 5,
    marginBottom: 10,
    paddingHorizontal: 15,
  },
  icon: {
    width: 24,
    height: 24,
  },
  activenumber: {
    fontSize: 12,
    fontFamily: 'Satoshi-Black',
    color: '#FFF',
  },
  inactivenumber: {
    fontSize: 12,
    fontFamily: 'Satoshi-Black',
    color: '#000',
  },
  // Dropdown (GradeLevelDropDownSelection)
  dropdownButton: {
    flexDirection: 'row',
    width: formWidth,
    height: 40,
    borderRadius: 5,
    backgroundColor: '#fff',
    justifyContent: 'flex-end',
    alignSelf: 'center',
    elevation: 5,
  },
  dropdownArrowicon: {
    marginLeft: 'auto',
    marginRight: 15,
  },
  dropdownContainer: {
    backgroundColor: '#fff',
    width: formWidth,
    height: 40,
    justifyContent: 'center',
    alignSelf: 'center',
    elevation: 5,
    borderRadius: 5,
  },
  // Complete Sign Up Page (if reused)
  completeSignUpContainer: {
    flex: 1,
    backgroundColor: '#ECFBFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  video: {
    width: Math.min(screenWidth - 40, 412),
    height: Math.min(screenWidth - 40, 412),
    marginBottom: 20,
    borderRadius: 20,
    overflow: 'hidden',
  },
  completeTitle: {
    color: '#2CA96A',
    fontFamily: 'Satoshi-Bold',
    fontSize: 35,
    textShadowColor: '#0000004D',
    textShadowOffset: { width: 4, height: 0 },
    textShadowRadius: 10,
    textAlign: 'center',
    width: '100%',
  },
  completeStatement: {
    textAlign: 'justify',
    paddingHorizontal: 20,
    paddingTop: 50,
    fontSize: 15,
    fontFamily: 'Satoshi-Regular',
  },
  completeNextButton: {
    backgroundColor: '#2CA96A',
    borderRadius: 5,
    width: Math.min(screenWidth - 40, 370),
    height: 40,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    fontFamily: 'Satoshi-Medium',
    marginBottom: 10,
    marginTop: 20,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    elevation: 5,
    minWidth: 250,
    minHeight: 300,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  modalText: {
    marginTop: 20,
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    zIndex: 10,
  },
  successText: {
    color: '#4CAF50',
    fontSize: 18,
    fontWeight: 'bold',
  },
  confettiAnimation: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  congratulationsAnimation: {
    width: 200,
    height: 200,
    zIndex: 2,
    marginBottom: -20,
  },
  lottieAnimation: {
    width: 120,
    height: 120,
    marginBottom: -10,
  },
});

export default signup;