import { StyleSheet, Dimensions } from 'react-native';
import { sw, sh, sf } from '../Utils/responsive';

const { width: screenWidth } = Dimensions.get('window');

// Define a responsive width for form elements (90% of screen, but not wider than 350)
const formWidth = Math.min(screenWidth - sw(40), sw(350));

const signup = StyleSheet.create({
  container: {
    backgroundColor: '#f2f6ff',
    padding: sw(20),
    flex: 1,
  },
  ciscLogo: {
    width: sw(90),
    height: sw(33),
    alignSelf: 'center', // Center logo
    marginVertical: sh(10),
  },
  label: {
    fontSize: sf(35),
    fontFamily: 'Satoshi-Bold',
    textShadowColor: '#0000004D',
    textShadowOffset: { width: 4, height: 0 },
    textShadowRadius: 10,
    textAlign: 'center',
    marginVertical: sh(10),
  },
  subLabel: {
    fontSize: sf(20),
    fontFamily: 'Satoshi-Black',
    textAlign: 'center',
    color: '#3B7FC9',
    marginBottom: sh(20),
  },
  defaultProfile: {
    width: sw(100),
    height: sw(100),
    borderRadius: sw(65),
    alignSelf: 'center',
    marginTop: sh(10),
  },
  cameraBackground: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#57b8b3',
    width: sw(36),
    height: sw(36),
    borderRadius: sw(18),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  cameraIcon: {
    width: sw(16),
    height: sw(16),
    tintColor: '#fff',
  },
  stepsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: sh(20),
  },
  stepCircle: {
    width: sw(24),
    height: sw(24),
    borderRadius: sw(12),
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepLine: {
    width: sw(40),
    height: 2,
    backgroundColor: 'black',
    marginHorizontal: sw(10),
  },
  activateStep: {
    backgroundColor: '#3B7FC9',
  },
  inactivateStep: {
    backgroundColor: '#FFFFFF',
  },
  // Form elements
  textform: {
    textAlign: 'left',
    fontSize: sf(15),
    fontFamily: 'Satoshi-Bold',
    marginHorizontal: sw(20),
    marginTop: sh(10),
    marginBottom: sh(5),
  },
  textInputForm: {
    width: formWidth,
    height: sh(40),
    borderRadius: sw(5),
    padding: sw(10),
    marginBottom: sh(10),
    backgroundColor: 'white',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    alignSelf: 'center',
    fontFamily: 'Satoshi-Medium',
    color: 'black',
  },
  dateText: {
    textAlign: 'left',
    fontSize: sf(15),
    fontFamily: 'Satoshi-Regular',
    marginHorizontal: sw(20),
  },
  dateInput: {
    flexDirection: 'row',
    width: formWidth,
    height: sh(40),
    borderRadius: sw(5),
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    marginBottom: sh(10),
    paddingHorizontal: sw(15),
  },
  icon: {
    width: sw(24),
    height: sw(24),
  },
  activenumber: {
    fontSize: sf(12),
    fontFamily: 'Satoshi-Black',
    color: '#FFF',
  },
  inactivenumber: {
    fontSize: sf(12),
    fontFamily: 'Satoshi-Black',
    color: '#000',
  },
  // Dropdown (GradeLevelDropDownSelection)
  dropdownButton: {
    flexDirection: 'row',
    width: formWidth,
    height: sh(40),
    borderRadius: sw(5),
    backgroundColor: '#fff',
    justifyContent: 'flex-end',
    alignSelf: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
  },
  dropdownArrowicon: {
    marginLeft: 'auto',
    marginRight: sw(15),
  },
  dropdownContainer: {
    backgroundColor: '#fff',
    width: formWidth,
    height: sh(40),
    justifyContent: 'center',
    alignSelf: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    borderRadius: sw(5),
  },
  // Complete Sign Up Page (if reused)
  completeSignUpContainer: {
    flex: 1,
    backgroundColor: '#ECFBFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: sw(20),
  },
  video: {
    width: Math.min(screenWidth - sw(40), sw(412)),
    height: Math.min(screenWidth - sw(40), sw(412)),
    marginBottom: sh(20),
    borderRadius: sw(20),
    overflow: 'hidden',
  },
  completeTitle: {
    color: '#2CA96A',
    fontFamily: 'Satoshi-Bold',
    fontSize: sf(35),
    textShadowColor: '#0000004D',
    textShadowOffset: { width: 4, height: 0 },
    textShadowRadius: 10,
    textAlign: 'center',
    width: '100%',
  },
  completeStatement: {
    textAlign: 'justify',
    paddingHorizontal: sw(20),
    paddingTop: sh(50),
    fontSize: sf(15),
    fontFamily: 'Satoshi-Regular',
  },
  completeNextButton: {
    backgroundColor: '#2CA96A',
    borderRadius: sw(5),
    width: Math.min(screenWidth - sw(40), sw(370)),
    height: sh(40),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    fontFamily: 'Satoshi-Medium',
    marginBottom: sh(10),
    marginTop: sh(20),
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    backgroundColor: 'white',
    borderRadius: sw(20),
    padding: sw(30),
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: sw(2) },
    shadowOpacity: 0.25,
    shadowRadius: sw(3.84),
    minWidth: sw(250),
    minHeight: sh(300),
    justifyContent: 'center',
    overflow: 'hidden',
  },
  modalText: {
    marginTop: sh(20),
    fontSize: sf(16),
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    zIndex: 10,
  },
  successText: {
    color: '#4CAF50',
    fontSize: sf(18),
    fontWeight: 'bold',
  },
  confettiAnimation: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  congratulationsAnimation: {
    width: sw(200),
    height: sw(200),
    zIndex: 2,
    marginBottom: sh(-20),
  },
  lottieAnimation: {
    width: sw(120),
    height: sw(120),
    marginBottom: sh(-10),
  },
});

export default signup;