import { Timestamp } from '@react-native-firebase/firestore';
import { MiscueType } from './miscue';

export interface MiscueReport {
  studentId: string;
  substitution: string;
  omission: string;
  insertion: string;
  repetition: string;
  timestamp: Date;
}
/**
 * TYPES OF USER ROLES
 *  - used in base user information
 */
export type UserRole = 'student' | 'faculty' | 'admin';

/**
 * USER DOCUMENT INTERFACE
 * - used to store user information
 */
export interface UserDocument {
  // USER ID
  uid: string;
  email?: string;
  role: UserRole;

  // USER PROFILE INFORMATION
  profileImageUrl?: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  sex: string;

  // ROLE SPECIFIC DATA
  // Student specific data
  studentData?: {
    gradeLevel: number;
    dateOfBirth?: string;
    classCode?: string;
    reading_Level?: 'beginner' | 'emerging' | 'intermediate' | 'advanced';
    readingLevelUpdatedAt?: Timestamp;
    parentConsent: {
      confirmed: boolean;
    };
  };

  // Faculty specific data
  facultyData?: {
    assignedGradeLevels: number[];
    assignedClassIds: string[];
  };

  // Admin specific data
  // adminData?: {
  //   permissions?: string[];
  //   isSuperAdmin?: boolean;
  //   lastLoginAt?: any;
  // };

  // Creation and update from Firestore Timestamp
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

/**
 * CLASS DOCUMENT INTERFACE
 * - used to store class information
 */
export interface ClassDocument {
  // Class specific data
  classId: string; // Automatically generated by the system
  classCode: string; // Human-readable code, e.g., "GR1-A" where code is generated for the students to join
  className?: string; // Optional: full class name
  gradeLevel: number;
  acadYear: string; // Ex. 2025-2026

  // References
  facultyId: string; // Reference to the faculty document (UID)
  studentIds: string[]; // Reference to the student documents (UIDs)
  // ─── Added for student acceptance or rejection to a class by faculty ───
  // pendingStudentIds — UIDs awaiting faculty approval. Promoted into
  // studentIds on accept, simply dropped on reject. Optional for back-compat
  // with classes created before this field existed.
  pendingStudentIds?: string[];
  // ─── End ──────────────────────────────────────────────────────────────
  status: 'active' | 'archived';

  archivedAt?: Timestamp;
  archivedBy?: string;

  // Creation and update from Firestore Timestamp
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

// ─── Added for student acceptance or rejection to a class by faculty ───────────
/**
 * STUDENT CLASS STATE
 *  - Discriminated union returned by resolveStudentClassState().
 *  - 'pending'  → student's UID is in some class's pendingStudentIds
 *  - 'active'   → student is enrolled (in studentIds AND has classCode set)
 *  - 'none'     → student has no class and no pending request
 *  - No 'rejected' variant: rejection silently removes the UID from
 *    pendingStudentIds, so the student simply returns to 'none' on next read.
 */
export type StudentClassState =
  | { kind: 'pending'; class: ClassDocument }
  | { kind: 'active'; class: ClassDocument }
  | { kind: 'none' };
// ─── End — student acceptance or rejection to a class by faculty ───────────────

/**
 * MISCUE REPORT DOCUMENT INTERFACE
 * - used to store miscue report information
 */
export interface MiscueReportDocument {
  reportId: string;
  studentId: string;

  /**
   * ADD THIS NEXT TIME FOR FUTURE PROOFING
   * Can be used for exporting student information for a class
   *
   * - Viewing historical performance
   * - Longitudinal reading analysis
   * - Adviser-approved analytics
   *
   */
  // classId: string;
  // acadYear: string;

  // Passage Information
  passageTitle: string;

  // Overall Overview before aside from storing in array
  substitution: string;
  omission: string;
  insertion: string;
  repetition: string;

  // Miscue Data (Stored in Array for Flexibility)
  miscues: {
    type: MiscueType;
    expectedWord: string; // Word in passage
    spokenWord?: string; // What student said (null for omissions)
  }[];

  // Performance Metrics
  totalWords: number;
  accuracyRate: number;
  wordPerMin: number;
  wordCorrectPerMin?:number,
  recordingDuration?: string;

  substitutionCount: number;
  omissionCount: number;
  insertionCount: number;
  repetitionCount: number;

  // Creation from Firestore Timestamp
  createdAt: Timestamp;
}

/**
 * Blueprint for creating a passage
 * Passages are managed globally by Admins and categorised by grade level.
 */
export interface PassageDocument {
  pid: string;
  title: string;
  author: string | null;
  passageText: string;
  createdAt: Timestamp;
}

/**
 * WORD COMPLETION DOCUMENT REPORT INTERFACE
 *  - used to store completed words
 */
export interface AlphabetReportDocument {
  alphabetId: string;
  studentId: string;
  letter: string;
  createdAt: Timestamp;
}

// Session summary document (fastest to query)
export interface AlphabetSessionReport {
  alphabetSessionId: string;
  studentId: string;
  dateKey: string;
  sessionDateAt: Timestamp;

  // totalLetters: number; // 26
  correctCount: number; // e.g. 18
  attemptedCount: number; // usually 26 for alphabet test

  correctLetters: string[]; // ["A","B","D"...]
  incorrectLetters: string[]; // optional but very useful
}

export type AlphabetAttemptUpdate = {
  incAttempted?: boolean;
  incCorrect?: boolean;
  addCorrect?: boolean;
  addIncorrect?: boolean;
  removeIncorrect?: boolean;
};

/**
 * Used for creating a session based data for data visualization of students progress
 */
export interface AlphabetSessionData {
  alphabetSessionId: string; // "${uid}_${YYYYMMDD}"
  studentId: string;
  date: string; // "YYYYMMDD"
  displayDate: string; // "Feb 19"
  attemptedCount: number;
  correctCount: number;
  correctLetters: string[];
  incorrectLetters: string[];
}

// WORD SESSION

/**
 * WORD COMPLETION DOCUMENT REPORT INTERFACE
 *  - used to store completed words
 */
export interface WordReportDocument {
  wordId: string;
  studentId: string;
  word: string;
  chapter: string;
  createdAt: Timestamp;
}

/**
 * A Firebase Document
 * These are the data used to compute the Word reading mastery and accuracy
 * Which are then used for data visualization of their reading progress
 */
export interface WordSessionReport {
  wordSessionId: string;
  studentId: string;
  dateKey: string; // YYYYMMDD (for range queries)
  startedAt: Timestamp;
  isCompleted?: boolean;
  sessionCompletedAt?: Timestamp | Date;

  totals: {
    attempted: number;
    correct: number;
  };

  chapters: Record<
    string, // "ch_1"
    {
      chapterId: number;
      chapterTitle: string;
      attempted: number; // optional but recommended
      correct: number; // optional but recommended

      lessons: Record<
        string, // "ls_1"
        {
          lessonId: number;
          lessonTitle: string;
          attempted: number;
          correct: number;
          targetWords: string[];
          correctWords: string[];
          incorrectWords: string[];
        }
      >;
    }
  >;
}

/**
 * Not a firebase document
 * A blueprint for updating the Word Session of a student
 */
export type WordAttemptUpdate = {
  incAttempted?: boolean;
  incCorrect?: boolean;
  addTargetWord?: boolean; // usually true on firstAttempt
  addCorrectWord?: boolean; // true when word becomes correct (firstCorrect)
  addIncorrectWord?: boolean; // true when firstAttempt is incorrect and not yet correct
  removeIncorrectWord?: boolean; // true when it becomes correct
};

// For navigation
/**
 * Not a firebase document
 * A blueprint for passing the data from Reading Selection to Reading Activity Sceen
 */
export type WordContext = {
  chapterId: number;
  chapterTitle: string;
  lessonId: number;
  lessonTitle: string;
  targetWord: string;
};

/**
 * Similar to Word Session Report interface
 *
 * A blueprint for storing data after reading attempt
 *
 * WILL DELETE LATER and use the Word Session Report interface
 *  - to avoid redanduncy
 */
export interface WordSessionData {
  wordSessionId: string;
  studentId: string;

  dateKey: string; // YYYYMMDD
  displayDate: string; // "Feb 19"

  attemptedCount: number;
  correctCount: number;

  // aggregated structure saved in Firestore (Option A)
  chapters: Record<
    string,
    {
      chapterId: number;
      chapterTitle: string;
      attempted?: number;
      correct?: number;

      lessons: Record<
        string,
        {
          lessonId: number;
          lessonTitle: string;
          attempted: number;
          correct: number;
        }
      >;
    }
  >;
}

/**
 * Similar to Word Session Report interface
 *
 * A blueprint for storing data after reading attempt
 *
 * MIGHT DELETE LATER and use the Word Session Report interface
 */
export interface WordPeriodSlot {
  label: string;
  sessions: WordSessionData[];

  // performance
  accuracy: number | null; // weighted: sum(correct)/sum(attempted)*100

  // aggregates
  attemptedCount: number;
  correctCount: number;

  // optional breakdowns for UI
  lessonAgg: Record<
    string, // "ch_1::ls_2"
    {
      chapterId: number;
      chapterTitle: string;
      lessonId: number;
      lessonTitle: string;
      attempted: number;
      correct: number;
      accuracy: number | null;
    }
  >;
}

/**
 * Not a Firebase Document
 *
 * A blueprint for accuracy computations for every session created by the user (student)
 */
export interface WordAccuracySummary {
  totalSessions: number;
  avgAccuracy: number | null;
}

export type LessonKey = `ch_${number}::ls_${number}`;
export type ChapterKey = `ch_${number}`;

export interface WordMasterySummary {
  totalCompleted: number; // total unique completed words
  masteryPercent: number | null; // totalCompleted / totalWordsInCurriculum * 100
  perLessonCompleted: Record<string, number>; // "ch_1::ls_2" -> count
}
