import { MiscueType } from "./miscue";
export interface MiscueReport {
  studentId: string;
  substitution: string;
  omission: string;
  insertion: string;
  repetition: string;
  timestamp: Date;
};
/**
 * TYPES OF USER ROLES
 *  - used in base user information
 */
export type UserRole = 'student' | 'faculty' | 'admin';


/**
 * USER DOCUMENT INTERFACE
 * - used to store user information
 */
export interface UserDocument {
  // USER ID
  uid: string;
  email: string;
  role: string;

  // USER PROFILE INFORMATION
  profileImageUrl?: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  sex: string;
  
  // ROLE SPECIFIC DATA
  // Student specific data
  studentData?: {
    gradeLevel: number;
    dateOfBirth?: string;
    classCode?: string;
    reading_Level?: 'beginner' | 'intermediate' | 'advanced';
  };

  // Faculty specific data
  facultyData?: {
    assignedGradeLevels: number[];
    assignedClassIds: string[];
  };

  // Creation and update from Firestore Timestamp
  createdAt: any; 
  updatedAt?: any; 
}

/**
 * CLASS DOCUMENT INTERFACE
 * - used to store class information
 */
export interface ClassDocument {
  // Class specific data
  classId: string; // Automatically generated by the system
  classCode: string; // Human-readable code, e.g., "GR1-A" where code is generated for the students to join
  className?: string; // Optional: full class name
  gradeLevel: number; 
  acadYear: string; // Ex. 2025-2026
  // term?: string; // For quarterly/semester systems


  // References
  facultyId: string; // Reference to the faculty document (UID)
  studentIds: string[]; // Reference to the student documents (UIDs)

  // META
  isActive: boolean;
  // Creation and update from Firestore Timestamp
  createdAt: any; 
  updatedAt?: any; 
}

/**
 * MISCUE REPORT DOCUMENT INTERFACE
 * - used to store miscue report information
 */
export interface MiscueReportDocument {
  reportId: string;
  studentId: string;

  // Passage Information
  passageTitle: string;

  // Overall Overview before aside from storing in array
  substitution: string;
  omission: string;
  insertion: string;
  repetition: string;

  // Miscue Data (Stored in Array for Flexibility)
  miscues: {
    type: MiscueType;
    expectedWord: string; // Word in passage
    spokenWord?: string; // What student said (null for omissions)
  }[];
  
  // Performance Metrics
  totalWords: number;
  accuracyRate: number;
  wordPerMin: number;
  recordingDuration?: string;
  totalMiscues?: number;
  substitutionCount?: number;
  omissionCount?: number;
  insertionCount?: number;
  repetitionCount?: number;

  // Creation from Firestore Timestamp
  timestamp: any;
}



